export const SET_TRUCK_DETAILS = 'SET_TRUCK_DETAILS';
export const SET_EXPENSES = 'SET_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_COMMISSIONS = 'SET_COMMISSIONS';
export const ADD_COMMISSION = 'ADD_COMMISSION';
export const DELETE_COMMISSION = 'DELETE_COMMISSION';
